name: Expenses Plugin Deployment

on:
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2   

      - name: Git Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZURI_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
          script: |
            cd /var/www/expenses.zuri.chat
            git pull origin dev
            git branch -r
            sudo rm composer.lock
            composer install
            npm run production
